//! The shipped guard queries, exported as data for `effinterp-bench`, which
//! evaluates them against the corpus plans without depending on Nah.

// The export is a repository file this test reads and rewrites.
#![allow(clippy::disallowed_methods)]

use std::path::Path;

const EXPORT: &str = "../../bench/nah/guard-queries.json";

/// `bench/nah/guard-queries.json` must match `shipped_guard_definitions()`.
/// A stale file is rewritten and the test fails; review the diff and rerun.
#[test]
fn exported_guard_queries_are_current() {
    let shipped = nah_policy::ShippedGuards::new();
    let guards = shipped
        .definitions()
        .iter()
        .map(|definition| {
            let clauses = definition
                .clauses
                .iter()
                .map(|clause| {
                    serde_json::json!({
                        "query": clause.query,
                        "needs_policy_context": clause.host.is_some()
                            || !clause.qualifiers.is_empty(),
                    })
                })
                .collect::<Vec<_>>();
            serde_json::json!({ "id": definition.id, "clauses": clauses })
        })
        .collect::<Vec<_>>();
    // One guard per line: the secret queries carry large path catalogs, and
    // pretty-printing them would multiply the file several times over.
    let header = serde_json::json!({
        "schema": "nah/guard-queries/v2",
        "_doc": [
            "Generated by the nah-policy suite test guard_queries::exported_guard_queries_are_current; do not edit.",
            "Each shipped guard in evaluation order: it matches when any clause does. A clause's query is a matcher query, answered with conclusive absence; `needs_policy_context` says Nah still applies a host rule or qualifier after the query matches."
        ],
    });
    let header = serde_json::to_string_pretty(&header).unwrap();
    let guards = guards
        .iter()
        .map(|guard| format!("    {guard}"))
        .collect::<Vec<_>>()
        .join(",\n");
    let expected = format!(
        "{},\n  \"guards\": [\n{guards}\n  ]\n}}\n",
        header.strip_suffix("\n}").unwrap()
    );
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join(EXPORT);
    let actual = std::fs::read_to_string(&path).unwrap_or_default();
    if actual != expected {
        std::fs::write(&path, expected).unwrap();
        panic!(
            "{} was stale and has been rewritten; review the diff and rerun",
            path.display()
        );
    }
}
