[source.effinterp]
git = "https://github.com/manuelschipper/effectinterp.git"
rev = "80ad17d8f48828565369c92a372b321c6124fc11"
replace-with = "effinterp-stubs"

[source.effinterp-stubs]
directory = "vendor/effinterp-stubs"
