[source.effinterp]
git = "https://github.com/manuelschipper/effectinterp.git"
rev = "41f707b9b127e2d974368f99e4c17891b06d8920"
replace-with = "effinterp-stubs"

[source.effinterp-stubs]
directory = "vendor/effinterp-stubs"
