[package]
name = "nah-policy"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
effinterp-matcher = { path = "../effinterp-matcher" }
effinterp-proto = { path = "../effinterp-proto" }
nah-proto = { path = "../nah-proto" }

[dev-dependencies]
serde_json = { workspace = true }
