//! `ClientSpec`, the option vocabulary and input grammar of one SQL client,
//! and the spec of each modeled client (psql, mysql, sqlite3, duckdb,
//! cockroach sql, cqlsh, clickhouse, sqlcmd, snowsql, snow sql).

use effinterp_proto::SqlDialect;

use super::sql_client_commands::Meta;
use super::{MYSQL_SCHEMES, PG_SCHEMES};

/// How a client reads its non-option operands.
#[derive(Clone, Copy, PartialEq, Eq)]
pub(super) enum Operands {
    /// A database name (or connection string), then up to `max - 1` more
    /// operands the client accepts but this model does not track (psql's user).
    Database {
        max: usize,
    },
    /// A database file, then SQL arguments each run in turn (sqlite3, duckdb).
    FileThenSql,
    /// `[host [port]]` (cqlsh).
    HostPort,
    /// A connection URL at most (clickhouse-client).
    Url,
    None,
}

/// Client-side text substitution that rewrites SQL before the server sees it.
#[derive(Clone, Copy, PartialEq, Eq)]
pub(super) enum Substitution {
    None,
    /// sqlcmd scripting variables, `$(name)`.
    Sqlcmd,
    /// SnowSQL variables, `&name` and `&{name}`, when a config enables them.
    Snowsql,
    /// Snowflake CLI templates, `&{ name }` and `<% name %>`.
    SnowCli,
    /// psql variables, `:name`, `:'name'` and `:"name"`, outside literals.
    /// psql does not interpolate `-c` SQL.
    Psql,
}

impl Substitution {
    /// Whether the client would rewrite `sql`. psql is not answered here:
    /// its bindings are tracked, so `Run::psql_sql` interpolates instead.
    pub(super) fn applies(self, sql: &str) -> bool {
        match self {
            Substitution::None | Substitution::Psql => false,
            Substitution::Sqlcmd => sql.contains("$("),
            Substitution::Snowsql => sql.as_bytes().windows(2).any(|pair| {
                pair[0] == b'&'
                    && (pair[1] == b'{' || pair[1].is_ascii_alphabetic() || pair[1] == b'_')
            }),
            Substitution::SnowCli => sql.contains("&{") || sql.contains("<%"),
        }
    }
}

/// The option vocabulary and input grammar of one SQL client.
pub(super) struct ClientSpec {
    pub(super) dialect: SqlDialect,
    pub(super) meta: Meta,
    /// Flags whose value is SQL the client runs, and then exits.
    pub(super) sql: &'static [&'static str],
    /// Flags whose value is SQL run before the client goes on to stdin.
    pub(super) startup_sql: &'static [&'static str],
    /// Flags naming a script file the client runs, and then exits.
    pub(super) files: &'static [&'static str],
    /// Flags naming a script run before the client goes on to stdin.
    pub(super) startup_files: &'static [&'static str],
    /// A script flag's value may list several files separated by commas.
    pub(super) comma_files: bool,
    /// `-f -` reads the script from stdin.
    pub(super) dash_is_stdin: bool,
    pub(super) db: &'static [&'static str],
    pub(super) host: &'static [&'static str],
    pub(super) port: &'static [&'static str],
    /// Flags whose value is a connection URL.
    pub(super) url: &'static [&'static str],
    pub(super) url_schemes: &'static [&'static str],
    /// Flags naming a file the client writes output to (`|cmd` pipes it).
    pub(super) output: &'static [&'static str],
    /// Other value flags; they select nothing this model tracks.
    pub(super) values: &'static [&'static str],
    pub(super) switches: &'static [&'static str],
    /// Flags that print usage or a version, and exit.
    pub(super) help: &'static [&'static str],
    /// Flags whose value may only be attached (`-pSECRET`, `--password=x`).
    pub(super) attached_only: &'static [&'static str],
    /// Switches after which the client does not read stdin.
    pub(super) no_stdin: &'static [&'static str],
    /// When non-empty, stdin is SQL only when one of these switches is given.
    pub(super) stdin_flags: &'static [&'static str],
    /// Unknown `--name=value` options are server settings (clickhouse-client).
    pub(super) setting_options: bool,
    /// Options whose effect on the SQL input is not modeled, with why.
    pub(super) unmodeled_values: &'static [(&'static str, &'static str)],
    /// Flags whose value is the statement delimiter the client starts with.
    pub(super) delimiter: &'static [&'static str],
    pub(super) operands: Operands,
    pub(super) scheme: Option<&'static str>,
    /// Endpoint the client connects to when argv selects none.
    pub(super) default_host: Option<&'static str>,
    pub(super) substitution: Substitution,
    /// Each SQL argument is one client command (when it starts with the
    /// command prefix) or else SQL the client sends verbatim.
    pub(super) single_command_args: bool,
    /// Flags naming a Snowflake account, which selects the server.
    pub(super) account: &'static [&'static str],
    /// Flags naming the account's region, part of its server name.
    pub(super) region: &'static [&'static str],
    /// Flags selecting a named connection from the client's configuration.
    pub(super) named_connection: &'static [&'static str],
}

pub(super) const CLIENT: ClientSpec = ClientSpec {
    dialect: SqlDialect::Generic,
    meta: Meta::None,
    sql: &[],
    startup_sql: &[],
    files: &[],
    startup_files: &[],
    comma_files: false,
    dash_is_stdin: false,
    db: &[],
    host: &[],
    port: &[],
    url: &[],
    url_schemes: &[],
    output: &[],
    values: &[],
    switches: &[],
    help: &[],
    attached_only: &[],
    no_stdin: &[],
    stdin_flags: &[],
    setting_options: false,
    unmodeled_values: &[],
    delimiter: &[],
    operands: Operands::None,
    scheme: None,
    default_host: None,
    substitution: Substitution::None,
    single_command_args: false,
    account: &[],
    region: &[],
    named_connection: &[],
};

impl ClientSpec {
    pub(super) fn value_flags(&self) -> Vec<&'static str> {
        let mut flags = Vec::new();
        for group in [
            self.sql,
            self.startup_sql,
            self.files,
            self.startup_files,
            self.db,
            self.host,
            self.port,
            self.url,
            self.output,
            self.values,
        ] {
            flags.extend_from_slice(group);
        }
        flags.extend_from_slice(self.account);
        flags.extend_from_slice(self.region);
        flags.extend_from_slice(self.named_connection);
        flags.extend(self.unmodeled_values.iter().map(|(flag, _)| *flag));
        flags.extend_from_slice(self.delimiter);
        flags
    }

    pub(super) fn known_flags(&self) -> Vec<&'static str> {
        let mut flags = Vec::new();
        for group in [
            self.switches,
            self.help,
            self.attached_only,
            self.no_stdin,
            self.stdin_flags,
        ] {
            flags.extend_from_slice(group);
        }
        flags
    }
}

pub(super) const PSQL: ClientSpec = ClientSpec {
    dialect: SqlDialect::Postgres,
    meta: Meta::Psql,
    sql: &["-c", "--command"],
    files: &["-f", "--file"],
    dash_is_stdin: true,
    db: &["-d", "--dbname"],
    host: &["-h", "--host"],
    port: &["-p", "--port"],
    output: &["-o", "--output", "-L", "--log-file"],
    values: &[
        "-v",
        "--set",
        "--variable",
        "-U",
        "--username",
        "-P",
        "--pset",
        "-F",
        "--field-separator",
        "-R",
        "--record-separator",
        "-T",
        "--table-attr",
    ],
    switches: &[
        "-a",
        "--echo-all",
        "-A",
        "--no-align",
        "-b",
        "--echo-errors",
        "--csv",
        "-e",
        "--echo-queries",
        "-E",
        "--echo-hidden",
        "-H",
        "--html",
        "-l",
        "--list",
        "-n",
        "--no-readline",
        "-q",
        "--quiet",
        "-s",
        "--single-step",
        "-S",
        "--single-line",
        "-t",
        "--tuples-only",
        "-x",
        "--expanded",
        "-X",
        "--no-psqlrc",
        "-z",
        "--field-separator-zero",
        "-0",
        "--record-separator-zero",
        "-1",
        "--single-transaction",
        "-w",
        "--no-password",
        "-W",
        "--password",
    ],
    help: &["-?", "--help", "-V", "--version"],
    url_schemes: PG_SCHEMES,
    operands: Operands::Database { max: 2 },
    scheme: Some("postgresql"),
    substitution: Substitution::Psql,
    single_command_args: true,
    ..CLIENT
};

pub(super) const MYSQL: ClientSpec = ClientSpec {
    dialect: SqlDialect::Mysql,
    meta: Meta::Mysql,
    sql: &["-e", "--execute"],
    startup_sql: &["--init-command"],
    db: &["-D", "--database"],
    host: &["-h", "--host"],
    port: &["-P", "--port"],
    output: &["--tee"],
    values: &[
        "-u",
        "--user",
        "-S",
        "--socket",
        "--default-character-set",
        "--defaults-file",
        "--defaults-extra-file",
        "--defaults-group-suffix",
        "--login-path",
        "--protocol",
        "--connect-timeout",
        "--max-allowed-packet",
        "--net-buffer-length",
        "--select-limit",
        "--max-join-size",
        "--prompt",
        "--ssl-ca",
        "--ssl-capath",
        "--ssl-cert",
        "--ssl-cipher",
        "--ssl-crl",
        "--ssl-crlpath",
        "--ssl-key",
        "--ssl-mode",
        "--tls-version",
        "--tls-ciphersuites",
        "--plugin-dir",
        "--default-auth",
        "--character-sets-dir",
        "--bind-address",
        "--compression-algorithms",
        "--zstd-compression-level",
        "--server-public-key-path",
        "--load-data-local-dir",
        "--histignore",
    ],
    switches: &[
        "-B",
        "--batch",
        "-N",
        "--skip-column-names",
        "--column-names",
        "-s",
        "--silent",
        "-v",
        "--verbose",
        "-t",
        "--table",
        "-H",
        "--html",
        "-X",
        "--xml",
        "-E",
        "--vertical",
        "-f",
        "--force",
        "-q",
        "--quick",
        "-r",
        "--raw",
        "-n",
        "--unbuffered",
        "-A",
        "--no-auto-rehash",
        "--auto-rehash",
        "--skip-auto-rehash",
        "-b",
        "--no-beep",
        "-c",
        "--comments",
        "--skip-comments",
        "-C",
        "--compress",
        "-G",
        "--named-commands",
        "--skip-named-commands",
        "-i",
        "--ignore-spaces",
        "-j",
        "--syslog",
        "-L",
        "--skip-line-numbers",
        "--line-numbers",
        "-o",
        "--one-database",
        "-U",
        "--safe-updates",
        "--i-am-a-dummy",
        "-w",
        "--wait",
        "-T",
        "--debug-info",
        "--binary-mode",
        "--binary-as-hex",
        "--skip-binary-as-hex",
        "--local-infile",
        "--no-defaults",
        "--print-defaults",
        "--show-warnings",
        "--sigint-ignore",
        "--reconnect",
        "--skip-reconnect",
        "--ssl",
        "--skip-ssl",
        "--ssl-verify-server-cert",
        "--enable-cleartext-plugin",
        "--get-server-public-key",
        "--skip-pager",
        "--no-pager",
        "--no-tee",
        "--skip-system-command",
        "-W",
        "--pipe",
    ],
    help: &["-?", "--help", "-V", "--version", "-I"],
    attached_only: &["-p", "--password"],
    delimiter: &["--delimiter"],
    unmodeled_values: &[("--pager", "mysql --pager sends query output to a command")],
    url_schemes: MYSQL_SCHEMES,
    operands: Operands::Database { max: 1 },
    ..CLIENT
};

/// sqlite3 accepts each option with one or two leading dashes.
pub(super) const SQLITE: ClientSpec = ClientSpec {
    dialect: SqlDialect::Sqlite,
    meta: Meta::Sqlite,
    startup_sql: &["-cmd", "--cmd"],
    startup_files: &["-init", "--init"],
    values: &[
        "-separator",
        "--separator",
        "-newline",
        "--newline",
        "-nullvalue",
        "--nullvalue",
        "-escape",
        "--escape",
        "-lookaside",
        "--lookaside",
        "-maxsize",
        "--maxsize",
        "-mmap",
        "--mmap",
        "-pagecache",
        "--pagecache",
        "-heap",
        "--heap",
        "-vfs",
        "--vfs",
    ],
    switches: &[
        "-append",
        "--append",
        "-ascii",
        "--ascii",
        "-bail",
        "--bail",
        "-batch",
        "--batch",
        "-box",
        "--box",
        "-column",
        "--column",
        "-csv",
        "--csv",
        "-deserialize",
        "--deserialize",
        "-echo",
        "--echo",
        "-header",
        "--header",
        "-noheader",
        "--noheader",
        "-html",
        "--html",
        "-interactive",
        "--interactive",
        "-json",
        "--json",
        "-line",
        "--line",
        "-list",
        "--list",
        "-markdown",
        "--markdown",
        "-memtrace",
        "--memtrace",
        "-nofollow",
        "--nofollow",
        "-quote",
        "--quote",
        "-readonly",
        "--readonly",
        "-safe",
        "--safe",
        "-stats",
        "--stats",
        "-table",
        "--table",
        "-tabs",
        "--tabs",
        "-zip",
        "--zip",
    ],
    help: &["-help", "--help", "-version", "--version"],
    operands: Operands::FileThenSql,
    single_command_args: true,
    ..CLIENT
};

pub(super) const DUCKDB: ClientSpec = ClientSpec {
    dialect: SqlDialect::Postgres,
    meta: Meta::Sqlite,
    sql: &["-c", "--c", "-s", "--s"],
    startup_sql: &["-cmd", "--cmd"],
    files: &["-f", "--f"],
    startup_files: &["-init", "--init"],
    values: &[
        "-separator",
        "--separator",
        "-newline",
        "--newline",
        "-nullvalue",
        "--nullvalue",
        "-storage-version",
        "--storage-version",
    ],
    switches: &[
        "-append",
        "--append",
        "-ascii",
        "--ascii",
        "-bail",
        "--bail",
        "-batch",
        "--batch",
        "-box",
        "--box",
        "-column",
        "--column",
        "-csv",
        "--csv",
        "-echo",
        "--echo",
        "-header",
        "--header",
        "-noheader",
        "--noheader",
        "-html",
        "--html",
        "-interactive",
        "--interactive",
        "-json",
        "--json",
        "-line",
        "--line",
        "-list",
        "--list",
        "-markdown",
        "--markdown",
        "-quote",
        "--quote",
        "-readonly",
        "--readonly",
        "-safe",
        "--safe",
        "-table",
        "--table",
        "-unredacted",
        "--unredacted",
        "-unsigned",
        "--unsigned",
    ],
    help: &["-help", "--help", "-version", "--version"],
    no_stdin: &["-no-stdin", "--no-stdin"],
    operands: Operands::FileThenSql,
    single_command_args: true,
    ..CLIENT
};

pub(super) const COCKROACH_SQL: ClientSpec = ClientSpec {
    dialect: SqlDialect::Postgres,
    meta: Meta::Psql,
    sql: &["-e", "--execute"],
    files: &["-f", "--file"],
    db: &["-d", "--database"],
    host: &["--host"],
    port: &["--port", "-p"],
    url: &["--url"],
    url_schemes: PG_SCHEMES,
    values: &[
        "-u",
        "--user",
        "--certs-dir",
        "--format",
        "--set",
        "--watch",
        "--cluster-name",
    ],
    switches: &[
        "--insecure",
        "--echo-sql",
        "--safe-updates",
        "--debug-sql-cli",
        "--no-line-editor",
        "--read-only",
        "--embedded",
    ],
    help: &["-h", "--help"],
    scheme: Some("postgresql"),
    default_host: Some("localhost"),
    ..CLIENT
};

pub(super) const CQLSH: ClientSpec = ClientSpec {
    dialect: SqlDialect::Cql,
    meta: Meta::Cql,
    sql: &["-e", "--execute"],
    files: &["-f", "--file"],
    db: &["-k", "--keyspace"],
    values: &[
        "-u",
        "--username",
        "-p",
        "--password",
        "--cqlshrc",
        "--encoding",
        "--cqlversion",
        "--protocol-version",
        "--connect-timeout",
        "--request-timeout",
        "-b",
        "--secure-connect-bundle",
        "--consistency-level",
        "--serial-consistency-level",
    ],
    switches: &[
        "--ssl",
        "--no-color",
        "-C",
        "--color",
        "--debug",
        "--no-file-io",
        "--disable-history",
        "-t",
        "--tty",
        "--insecure-password-without-warning",
    ],
    help: &["-h", "--help", "--version"],
    operands: Operands::HostPort,
    default_host: Some("127.0.0.1"),
    ..CLIENT
};

pub(super) const CLICKHOUSE: ClientSpec = ClientSpec {
    dialect: SqlDialect::ClickHouse,
    sql: &["-q", "--query"],
    files: &["--queries-file"],
    db: &["-d", "--database"],
    host: &["-h", "--host"],
    port: &["--port"],
    url_schemes: &["clickhouse"],
    values: &[
        "-u",
        "--user",
        "--password",
        "-C",
        "--config-file",
        "-f",
        "--format",
        "--connection",
        "--history_file",
        "--jwt",
    ],
    switches: &[
        "-m",
        "--multiline",
        "-n",
        "--multiquery",
        "-s",
        "--secure",
        "-t",
        "--time",
        "--stacktrace",
        "--progress",
        "--echo",
        "-E",
        "--vertical",
        "--ask-password",
        "--disable_suggestion",
        "-A",
    ],
    help: &["--help", "-V", "--version"],
    setting_options: true,
    operands: Operands::Url,
    ..CLIENT
};

pub(super) const SQLCMD: ClientSpec = ClientSpec {
    dialect: SqlDialect::TSql,
    meta: Meta::Sqlcmd,
    sql: &["-Q"],
    startup_sql: &["-q"],
    files: &["-i"],
    comma_files: true,
    db: &["-d"],
    host: &["-S"],
    output: &["-o"],
    values: &[
        "-U", "-P", "-v", "-f", "-h", "-s", "-w", "-t", "-l", "-a", "-m", "-V", "-H", "-K", "-z",
        "-Z", "-y", "-Y", "-F",
    ],
    switches: &[
        "-E", "-C", "-b", "-e", "-I", "-k", "-r", "-W", "-X", "-x", "-p", "-u", "-N", "-A", "-G",
        "-M", "-j",
    ],
    help: &["-?", "--help", "--version"],
    unmodeled_values: &[("-c", "sqlcmd -c changes the batch terminator")],
    substitution: Substitution::Sqlcmd,
    ..CLIENT
};

pub(super) const SNOWSQL: ClientSpec = ClientSpec {
    dialect: SqlDialect::Snowflake,
    meta: Meta::Snow,
    sql: &["-q", "--query"],
    files: &["-f", "--filename"],
    db: &["-d", "--dbname"],
    host: &["-h", "--host"],
    port: &["-p", "--port"],
    account: &["-a", "--accountname"],
    region: &["--region"],
    named_connection: &["-c", "--connection"],
    values: &[
        "-u",
        "--username",
        "-s",
        "--schemaname",
        "-r",
        "--rolename",
        "-w",
        "--warehouse",
        "-o",
        "--option",
        "-D",
        "--variable",
        "--config",
        "--authenticator",
        "--private-key-path",
        "--token",
        "--query_tag",
        "--mfa-passcode",
    ],
    switches: &[
        "-P",
        "--prompt",
        "-M",
        "--mfa-prompt",
        "-x",
        "--noup",
        "--abort-detached-query",
        "--generate-jwt",
    ],
    help: &["-?", "--help", "-v", "--version"],
    substitution: Substitution::Snowsql,
    ..CLIENT
};

pub(super) const SNOW_SQL: ClientSpec = ClientSpec {
    dialect: SqlDialect::Snowflake,
    meta: Meta::Snow,
    sql: &["-q", "--query"],
    files: &["-f", "--filename"],
    db: &["--database", "--dbname"],
    host: &["--host"],
    port: &["--port"],
    values: &[
        "-D",
        "--variable",
        "--environment",
        "--user",
        "--username",
        "--password",
        "--authenticator",
        "--workload-identity-provider",
        "--private-key-file",
        "--private-key-path",
        "--token",
        "--token-file-path",
        "--schema",
        "--schemaname",
        "--role",
        "--rolename",
        "--warehouse",
        "--mfa-passcode",
        "--format",
        "--diag-log-path",
        "--diag-allowlist-path",
        "-p",
        "--project",
        "--env",
        "--master-token",
        "--session-token",
        "--enable-templating",
    ],
    switches: &[
        "--retain-comments",
        "--single-transaction",
        "--no-single-transaction",
        "-x",
        "--temporary-connection",
        "--enable-diag",
        "-v",
        "--verbose",
        "--debug",
        "--silent",
        "--enhanced-exit-codes",
    ],
    help: &["-h", "--help"],
    stdin_flags: &["-i", "--stdin"],
    account: &["--account", "--accountname"],
    region: &["--region"],
    named_connection: &["-c", "--connection"],
    substitution: Substitution::SnowCli,
    ..CLIENT
};
