[package]
name = "nah-actions"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
nah-proto = { path = "../nah-proto" }
nah-parse = { path = "../nah-parse" }
nah-inline = { path = "../nah-inline" }

[dev-dependencies]
serde_json = "1"
