//! Repinning: recompute promoted document identities, regenerate their
//! whole-plan fixtures, and rewrite fixture digests and evidence-report
//! revisions together on disk.

use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

use effinterp_engine::{Catalog, Engine, compile_registry};
use effinterp_model_schema::{DeclarationDocument, FixtureDeclaration, MODEL_SCHEMA_V1};
use effinterp_proto::{Subject, content_digest};

use crate::FactoryError;
use crate::fixture_evidence::{projected_fixture_json, read_fact_assertion_fixture};
use crate::model_directory::{canonical_json, model_json_paths, read, write};
use crate::model_normalization::normalized_promoted;

/// Recompute promoted identities and repin their evidence together. Every
/// `.json` file in the `directory` tree must be a promoted model document.
///
/// The two fixture kinds are treated differently. `CanonicalPlans` fixtures are
/// regenerated by analyzing their subjects with the current models.
/// `FactAssertions` fixtures keep their bytes: they are only parsed and their
/// digest re-pinned; their cases, negative tests, and mutation checks are not run.
/// Repinning is therefore not verification: run [`verify_directory`] or
/// [`verify_directory_with_options`] afterwards to qualify the new evidence.
///
/// Writes happen in order, without a transaction: regenerated fixtures, then the
/// documents, then the optional `evidence` report. An I/O failure part way leaves
/// the earlier files rewritten.
///
/// [`verify_directory`]: crate::verify_directory
/// [`verify_directory_with_options`]: crate::verify_directory_with_options
pub fn repin_directory(directory: &Path, evidence: Option<&Path>) -> Result<(), FactoryError> {
    let paths = model_json_paths(directory)?;
    let mut documents = paths
        .iter()
        .map(|path| {
            let source = read(&directory.join(path))?;
            let document: DeclarationDocument = serde_json::from_str(&source)
                .map_err(|error| FactoryError::Json(error.to_string()))?;
            if document.schema != MODEL_SCHEMA_V1 {
                return Err(FactoryError::Validation(format!(
                    "unexpected promoted schema {:?}",
                    document.schema
                )));
            }
            Ok(normalized_promoted(&document))
        })
        .collect::<Result<Vec<_>, FactoryError>>()?;
    let sources = documents
        .iter()
        .map(canonical_json)
        .collect::<Result<Vec<_>, _>>()?;
    let refs = sources.iter().map(String::as_str).collect::<Vec<_>>();
    let registry =
        compile_registry(&refs).map_err(|error| FactoryError::Validation(error.to_string()))?;
    let revisions = registry
        .declaration_digests()
        .iter()
        .map(|(id, digest)| (id.clone(), format!("{id}#blake3:{digest}")))
        .collect::<BTreeMap<_, _>>();
    let identities = documents
        .iter()
        .flat_map(|document| {
            document
                .entries
                .iter()
                .map(|entry| (entry.id().to_string(), document.identity.clone()))
        })
        .collect::<BTreeMap<_, _>>();
    let engine = Engine::with_catalog(
        Catalog::from_registry(registry)
            .map_err(|error| FactoryError::Validation(error.to_string()))?,
    )
    .with_causality_detail(true);
    let mut regenerated_fixtures = BTreeMap::new();
    let mut fixture_digests = BTreeMap::new();
    for document in &documents {
        for fixture in &document.evidence.fixtures {
            match fixture {
                FixtureDeclaration::CanonicalPlans { path, .. } => {
                    if regenerated_fixtures.contains_key(path) {
                        continue;
                    }
                    let prior: Vec<serde_json::Value> =
                        serde_json::from_str(&read(&directory.join(path))?)
                            .map_err(|error| FactoryError::Json(error.to_string()))?;
                    let plans = prior
                        .into_iter()
                        .map(|value| {
                            let subject: Subject = serde_json::from_value(
                                value.get("subject").cloned().ok_or_else(|| {
                                    FactoryError::Validation(
                                        "fixture case has no subject".to_string(),
                                    )
                                })?,
                            )
                            .map_err(|error| FactoryError::Json(error.to_string()))?;
                            engine
                                .analyze(&subject)
                                .map_err(|error| FactoryError::Validation(error.to_string()))
                        })
                        .collect::<Result<Vec<_>, _>>()?;
                    let source = projected_fixture_json(&plans)?;
                    fixture_digests.insert(path.clone(), content_digest(source.as_bytes()));
                    regenerated_fixtures.insert(path.clone(), source);
                }
                FixtureDeclaration::FactAssertions { path, .. } => {
                    if fixture_digests.contains_key(path) {
                        continue;
                    }
                    let bytes =
                        fs::read(directory.join(path)).map_err(|error| FactoryError::Io {
                            path: directory.join(path),
                            detail: error.to_string(),
                        })?;
                    read_fact_assertion_fixture(&bytes).map_err(FactoryError::Validation)?;
                    fixture_digests.insert(path.clone(), content_digest(&bytes));
                }
                FixtureDeclaration::Registry { .. } => {}
            }
        }
    }
    let evidence_source = evidence
        .map(|path| {
            let original = read(path)?;
            let mut value: serde_json::Value = serde_json::from_str(&original)
                .map_err(|error| FactoryError::Json(error.to_string()))?;
            repin_evidence(&mut value, &revisions, &identities)?;
            let mut source = String::new();
            let mut cursor = 0;
            rewrite_evidence_strings(&original, &mut cursor, &value, &mut source);
            source.push_str(&original[cursor..]);
            Ok::<_, FactoryError>(source)
        })
        .transpose()?;
    for (path, source) in &regenerated_fixtures {
        write(&directory.join(path), source.as_bytes())?;
    }
    for (path, document) in paths.iter().zip(&mut documents) {
        for fixture in &mut document.evidence.fixtures {
            match fixture {
                FixtureDeclaration::CanonicalPlans { path, digest, .. }
                | FixtureDeclaration::FactAssertions { path, digest, .. } => {
                    *digest = fixture_digests[path].clone();
                }
                FixtureDeclaration::Registry { .. } => {}
            }
        }
        write(&directory.join(path), canonical_json(document)?.as_bytes())?;
    }
    if let (Some(path), Some(source)) = (evidence, evidence_source) {
        write(path, source.as_bytes())?;
    }
    Ok(())
}

// Keep the evidence report's existing key order and formatting while replacing values.
fn rewrite_evidence_strings(
    source: &str,
    cursor: &mut usize,
    value: &serde_json::Value,
    output: &mut String,
) {
    fn copy_space(source: &str, cursor: &mut usize, output: &mut String) {
        while source
            .as_bytes()
            .get(*cursor)
            .is_some_and(u8::is_ascii_whitespace)
        {
            output.push(source.as_bytes()[*cursor] as char);
            *cursor += 1;
        }
    }
    copy_space(source, cursor, output);
    match value {
        serde_json::Value::Object(object) => {
            output.push('{');
            *cursor += 1;
            copy_space(source, cursor, output);
            while source.as_bytes()[*cursor] != b'}' {
                let mut keys =
                    serde_json::Deserializer::from_str(&source[*cursor..]).into_iter::<String>();
                let key = keys.next().unwrap().unwrap();
                let end = *cursor + keys.byte_offset();
                output.push_str(&source[*cursor..end]);
                *cursor = end;
                copy_space(source, cursor, output);
                output.push(':');
                *cursor += 1;
                rewrite_evidence_strings(source, cursor, &object[&key], output);
                copy_space(source, cursor, output);
                if source.as_bytes()[*cursor] == b',' {
                    output.push(',');
                    *cursor += 1;
                    copy_space(source, cursor, output);
                }
            }
            output.push('}');
            *cursor += 1;
        }
        serde_json::Value::Array(values) => {
            output.push('[');
            *cursor += 1;
            for (index, value) in values.iter().enumerate() {
                if index > 0 {
                    output.push(',');
                    *cursor += 1;
                }
                rewrite_evidence_strings(source, cursor, value, output);
                copy_space(source, cursor, output);
            }
            copy_space(source, cursor, output);
            output.push(']');
            *cursor += 1;
        }
        _ => {
            let mut values = serde_json::Deserializer::from_str(&source[*cursor..])
                .into_iter::<serde_json::Value>();
            let original = values.next().unwrap().unwrap();
            let end = *cursor + values.byte_offset();
            if value != &original {
                output.push_str(&serde_json::to_string(value).unwrap());
            } else {
                output.push_str(&source[*cursor..end]);
            }
            *cursor = end;
        }
    }
}

fn repin_evidence(
    value: &mut serde_json::Value,
    revisions: &BTreeMap<String, String>,
    identities: &BTreeMap<String, String>,
) -> Result<(), FactoryError> {
    match value {
        serde_json::Value::String(text) => {
            if let Some((id, digest)) = text.split_once("#blake3:")
                && digest.len() == 64
                && digest.bytes().all(|byte| byte.is_ascii_hexdigit())
            {
                *text = revisions
                    .get(id)
                    .ok_or_else(|| {
                        FactoryError::Validation(format!("evidence references unpromoted id {id}"))
                    })?
                    .clone();
            }
        }
        serde_json::Value::Array(values) => {
            for value in values {
                repin_evidence(value, revisions, identities)?;
            }
        }
        serde_json::Value::Object(object) => {
            if let Some(models) = object
                .get_mut("model_revisions")
                .and_then(serde_json::Value::as_array_mut)
            {
                for model in models {
                    let id = model
                        .get("id")
                        .and_then(serde_json::Value::as_str)
                        .ok_or_else(|| {
                            FactoryError::Validation("model revision has no id".to_string())
                        })?;
                    let identity = identities
                        .get(id)
                        .ok_or_else(|| {
                            FactoryError::Validation(format!(
                                "evidence references unpromoted id {id}"
                            ))
                        })?
                        .clone();
                    if let Some(value) = model.get_mut("document_identity") {
                        *value = identity.into();
                    }
                }
            }
            for value in object.values_mut() {
                repin_evidence(value, revisions, identities)?;
            }
        }
        _ => {}
    }
    Ok(())
}
